version: '3'

tasks:
  run:
    desc: "Run the backend server with Neon DB connection"
    dir: .
    dotenv: ['.env']
    cmds:
      - go run ./cmd/api/main.go

  build:
    desc: "Build the backend binary (Output: server.exe)"
    cmds:
      - go build -o server.exe ./cmd/api/main.go

  up:
    desc: "Start backend and database services"
    cmds:
      - docker-compose -f ../docker-compose.yml up -d

  down:
    desc: "Stop backend and database services"
    cmds:
      - docker-compose -f ../docker-compose.yml down

  logs:
    desc: "View backend logs"
    cmds:
      - docker-compose -f ../docker-compose.yml logs -f backend
